# Apéndice A. Introducción a Python y NumPy

Este apéndice ha sido creado como un libro interactivo donde aprenderá a crear programas básicos en **Python** y usar la biblioteca matemática **NumPy** que es usada ampliamente en álgebra lineal y para la generación de señales en tiempo discreto. Si está familiarizado con Matlab verá que muchos comando soportados por NumPy se asemejan a la sintaxis de dicho entorno de simulación, con algunas excepciones como los operadores de multiplicación.  

Esta guía ha sido construida como un cuaderno de Python o _Jupiter Notebook_ el cual le permite ingresar celdas de texto (en un lenguaje llamado **Markdown**) o código interactivo en Python, las cuales puede ejecutar dando clic en el botón ▷. La Sección A.8 describe como crear dichos cuadernos.

# A.1. Instalación de bibliotecas

Si es novato en Python debe saber que éste es un lenguaje interpretado que emplea bibliotecas para correr los programas. Aunque existe un gran número de bibliotecas, estás pueden instalarse fácilmente desde el Terminal del su sistema operativo empleando el comando ``pip install [Nombrebiblioteca]``. En este apéndice aprenderá a manejar biblioteca **NumPy**, por lo que si es la primera vez que usa Python debe instalarla. 

Esta biblioteca se pueden instalar dando clic en el botón ▷ de la siguiente celda desde Jupyter o VSCode, o escribiendo la siguiente línea de código en un terminal (o consola) quitando el símbolo !. Si usa GoogleColab debe ejecutar obligatoriamente esta celda para instalarla en su entorno. Esta celda solamente debe ejecutarse una vez. Si ya tiene instalado numpy no necesita ejecutar esta celda.

In [ ]:
#Instala la biblioteca NumPy (Obligatorio si usa GoogleColab)
!pip install numpy

# A.2. Importación de bibliotecas

Todo programa en Python comienza con la importación de bibliotecas usando el comando ``import``. Al importar esta biblioteca se puede agregar la directiva ``as`` para darle un alias a la biblioteca, ya que todos los componentes de la biblioteca se acceden usando su nombre o el del alias.

A continuación se muestra como cargar la biblioteca **NumPy**. Nota: Si al ejecutar la celda en Jupyter o VSCode se produce un error **"ModuleNotFoundError"** debe instalar la biblioteca como se indicó anteriormente. No olvide dar clic en el botón ▷ para ejecutar una celda interactiva.

In [2]:
# Carga las biblioteca NumPy
import numpy as np

# A.3. Operadores, vectores y matrices

## A.3.1. Declarar vectores y matrices

Python es un lenguaje interpretado no tipado, eso significa que no es necesario declarar el tipo de dato de las variables como se haría en lenguaje C. Sin embargo, en aquellos casos en los cuales se requiere crear un vector o matriz inicializado se usa la siguiente sintaxis.

1. Crea un vector fila con valores inicializados:

In [3]:
a = np.array([1, -1, 4, 7, 2])
print(a)

[ 1 -1  4  7  2]


Es importante indicar que en Python es posible crear este vector de la forma
``a = [1, -1, 4, 7, 2]`` sin necesidad de anteponer ``np.array``. Sin embargo, esto crea un objeto del tipo ``list`` sobre el cual no es posible emplear muchas de las operaciones matemáticas de NumPy como se mostrará en próximos ejemplos, lo cual le podría generará errores de ejecución. La recomendación, es que si usa NumPy para hacer operaciones de álgebra lineal, cree siempre los vectores inicializados con ``np.array``.

Una forma alternativa de crear un vector fila, y que resulta conveniente para ciertas operaciones como el producto matriz-vector es usar doble ``[[`` y ``]]``. Aunque por lo general la primera forma que se mostró es la que más se usa en la mayoría de los casos. 

In [4]:
a = np.array([[1, -1, 4, 7, 2]])
print(a)

[[ 1 -1  4  7  2]]


2. Crea un vector columna con valores inicializados:

In [5]:
b = np.array([[2], [0], [1], [-1], [1]])
print(b)

[[ 2]
 [ 0]
 [ 1]
 [-1]
 [ 1]]


3. Crea un vector fila que contiene los valores entre ``límite_inferior`` y ``límite_superior``, con incrementos de 1, pero no incluye el límite superior: ``vector = np.arange(límite_inferior, límite_superior)``

In [7]:
c = np.arange(4,10)
print(c)

[4 5 6 7 8 9]


4. Crea un vector fila que contiene los valores entre ``límite_inferior`` hasta ``límite_superior`` con incrementos
definidos en ``paso``, sin incluir el límite superior: ``vector = np.arange(límite_inferior,límite_superior,paso)``

In [8]:
x = np.arange(-1.5, 1.5, 0.1)
print(x)

[-1.50000000e+00 -1.40000000e+00 -1.30000000e+00 -1.20000000e+00
 -1.10000000e+00 -1.00000000e+00 -9.00000000e-01 -8.00000000e-01
 -7.00000000e-01 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01
 -3.00000000e-01 -2.00000000e-01 -1.00000000e-01  1.33226763e-15
  1.00000000e-01  2.00000000e-01  3.00000000e-01  4.00000000e-01
  5.00000000e-01  6.00000000e-01  7.00000000e-01  8.00000000e-01
  9.00000000e-01  1.00000000e+00  1.10000000e+00  1.20000000e+00
  1.30000000e+00  1.40000000e+00]


5. Crea una matriz de la forma $\left[\begin{array}{ccc}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right]$

In [9]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6. Crea un vector fila inicializado con ceros ``np.zeros((1,tamaño))``

In [10]:
vector0 = np.zeros((1,7))
print(vector0)

[[0. 0. 0. 0. 0. 0. 0.]]


7. Crea una matriz de #filas × #columnas elementos inicializados con ceros ``np.zeros( (#filas, #columnas) )``

In [11]:
matriz0 = np.zeros((3,2))
print(matriz0)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


8. Crea una matriz de #filas×#columnas elementos inicializados con unos: ``np.ones( (#filas, #columnas) )``

In [12]:
matriz1 = np.ones( (3, 3) )
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Tanto los límites como los elementos anteriormente indicados pueden ser operaciones o variables. Veamos algunos ejemplos:

In [14]:
max = 5
step = .5
x = np.arange(-max,max,step)
print(x)

teta = np.pi/4
y = np.array( [[np.cos(teta), -np.sin(teta), 0], [np.sin(teta), np.cos(teta), 0], [0, 0, 1] ])
print(y)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5]
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


En el ejemplo anterior, se mostró también como usar las funciones trigonométricas seno y coseno de la biblioteca NumPy así como la constante numérica $\pi$ con ``np.pi``.

## A.3.2. Trabajar con vectores o matrices

### Productos de matrices
 
Todos los operadores y funciones básicas de NumPy están sobrecargados para trabajar con vectores y matrices, sin embargo, hay que tener en cuenta que, por defecto, todos los operados realizan operaciones componente-componente. Por ejemplo, supongamos que A y B son dos matrices 3 × 3. 

La línea de código ``A*B`` calcula el producto componente-componente de ambas matrices, es decir, 
$$\left[\begin{array}{ccc}
a_{11}\times b_{11} & a_{12}\times b_{12} & a_{13}\times b_{13}\\
a_{21}\times b_{21} & a_{22}\times b_{22} & a_{23}\times b_{23}\\
a_{31}\times b_{31} & a_{32}\times b_{32} & a_{33}\times b_{33}
\end{array}\right]$$

Por otra parte, si lo que se desea es el producto de las dos matrices, se debe usar la función ``np.dot(A,B)``, como se muestra en el siguiente ejemplo:

In [15]:
A = np.array([[3,2,6], [1,0,3], [5,1,2]])
B = np.array([[4,1,5], [7,3,1], [0,0,1]])
#Calcula el producto componente-componente de matrices
C = A * B
print(C)
#Calcula el producto de matrices
D = np.dot(A,B)
print(D)

[[12  2 30]
 [ 7  0  3]
 [ 0  0  2]]
[[26  9 23]
 [ 4  1  8]
 [27  8 28]]


### Productos de vectores

Algo similar ocurre cuando se multiplican vectores. Sí v1 y v2 son dos vectores fila, la línea de código ``v1*v2`` genera un vector cuyos elementos son el **producto componente-componente** de los vectores v1 y v2 $$\left[\begin{array}{ccc}
v_{11}\times v_{21} & v_{12}\times v_{22} & v_{13}\times v_{23}\end{array}\right]$$

In [17]:
v1 = np.array([2,3,4])
v2 = np.array([1,5,7])
v3 = v1 * v2
print(v3)

[ 2 15 28]


Si lo que se deseaba en el pasado cálculo era calcular el **producto punto**,

$$\boldsymbol{v}_{1}\circ\boldsymbol{v}_{2}=\boldsymbol{v}_{1}\boldsymbol{v}_{2}^{T}=\sum_{k=1}^{N}v_{1k}v_{2k}$$

es necesario usar la función ``np.dot``

In [18]:
producto_punto = np.dot(v1,v2)
print(producto_punto)

45


Un caso interesante de Python es que el operador multiplicación se comporta como un **producto tensorial** cuando se multiplica un vector fila y uno columna:

$$ \left[\begin{array}{ccc}
v_{11} & v_{12} & v_{13}\end{array}\right]\otimes\left[\begin{array}{c}
v_{21}\\
v_{22}\\
v_{23}
\end{array}\right]=\left[\begin{array}{ccc}
v_{11}\times\left[\begin{array}{c}
v_{21}\\
v_{22}\\
v_{23}
\end{array}\right] & v_{12}\times\left[\begin{array}{c}
v_{21}\\
v_{22}\\
v_{23}
\end{array}\right] & v_{13}\times\left[\begin{array}{c}
v_{21}\\
v_{22}\\
v_{23}
\end{array}\right]\end{array}\right]$$


In [19]:
a = np.array([1, 2, 3])
b = np.array([[-1], [2], [1]])
u = a*b
print(a)
print(b)
print(u)

[1 2 3]
[[-1]
 [ 2]
 [ 1]]
[[-1 -2 -3]
 [ 2  4  6]
 [ 1  2  3]]


### Operadores componente a componente

En la sección anterior se mostró que operadores como la multiplicación realizaban un producto componente-componente. Este comportamiento se extiende a todas las funciones de la biblioteca NumPy como se mostrará en los siguientes ejemplos: 

* Para elevar los elementos de un vector $v1 = [2 ~ 3 ~ 4]$ a la potencia indicada en el vector $v2 = [1 ~ 5 ~ 7]$, es decir, $v_3 =\left[\begin{array}{ccc}
2^1 & 3^5 & 4^7\end{array}\right]$


In [80]:
v1 = np.array([2,3,4])
v2 = np.array([1,5,7])
v3 = np.pow(v1,v2)
print(v3)

[    2   243 16384]


* Para el operador potenciación, ``np.pow``, cuando el elemento de la izquierda es un escalar, el vector resultante es igual al escalar elevado a cada una de los potencias indicadas en el vector. El siguiente ejemplo produce $w =\left[\begin{array}{ccc} 2^0 & 2^1 & 2^2 & 2^3 & 2^4 & 2^5 & 2^6 & 2^7\end{array}\right]$

In [20]:
n = np.arange(0,8)
w = np.pow(2, n)
print(w)

[  1   2   4   8  16  32  64 128]


* Como se indicó anteriormente, se pueden usar vectores o matrices como argumentos de entrada de todas las funciones de NumPy. En el siguiente ejemplo ``np.sin`` produce una matriz de salida que es igual al seno de cada elemento de la matriz de entrada:

In [21]:
m1 = np.array([[0, np.pi/2, -np.pi], [np.pi/4, 2*np.pi, np.pi]])
m2 = np.sin(m1)
print(m1)
print(m2)

[[ 0.          1.57079633 -3.14159265]
 [ 0.78539816  6.28318531  3.14159265]]
[[ 0.00000000e+00  1.00000000e+00 -1.22464680e-16]
 [ 7.07106781e-01 -2.44929360e-16  1.22464680e-16]]


### Producto de matrices y vectores

Una operación fundamental en álgebra lineal es el producto de una matriz por un vector columna para producir una transformación lineal del tipo
$$\boldsymbol{y}=\mathbf{A}\boldsymbol{x}=\left[\begin{array}{ccc}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{array}\right]\left[\begin{array}{c}
x_{1}\\
x_{2}\\
x_{3}
\end{array}\right]$$

Este cálculo se puede realizar con NumPy usando el operador ``np.dot`` de la siguiente forma:

In [22]:
A = np.array([[3,2,6], [1,0,3], [5,1,2]])
x = np.array([[0],[0],[1]])
y = np.dot(A,x)
print(A)
print(x)
print(y)

[[3 2 6]
 [1 0 3]
 [5 1 2]]
[[0]
 [0]
 [1]]
[[6]
 [3]
 [2]]


Sí x fuera un vector fila, sabemos desde el álgebra lineal que la operación $\boldsymbol{y}=\mathbf{A}\boldsymbol{x}$ es inválida, por lo que la única forma válida es $$\boldsymbol{y}=\mathbf{A}\boldsymbol{x}^T$$ con T indicando la transpuesta de x. Esto se puede escribir en NumPy de la siguiente forma:

In [23]:
A = np.array([[3,2,6], [1,0,3], [5,1,2]])
x = np.array([[0,0,1]])
y = np.dot(A, x.T)
print(A)
print(x)
print(y)

[[3 2 6]
 [1 0 3]
 [5 1 2]]
[[0 0 1]]
[[6]
 [3]
 [2]]


El programa anterior funcionó porque x fue definido como un vector fila con doble ``[[`` y ``]]``. Sin embargo si se hubiera definido con un solo ``[``, como ``x = np.array([0,0,1])``. El código produce un resultado matemático correcto pero empaquetado en un vector fila y no columna como se muestra a continuación:

In [24]:
A = np.array([[3,2,6], [1,0,3], [5,1,2]])
x = np.array([0,0,1])
y = np.dot(A, x.T)
print(A)
print(x)
print(y)

[[3 2 6]
 [1 0 3]
 [5 1 2]]
[0 0 1]
[6 3 2]


# A.4. Acceso a elementos de matrices y vectores

Para acceder individualmente a los elementos de matrices y vectores se emplea la siguiente notación:
* ``elemento = vector[posición]``
* ``subvector_elementos = vector[vector_posiciones]``
* ``elemento = matriz[fila,columna]``
* ``submatriz_elementos = matriz[vector_filas,vector_columnas]``

Cabe resaltar que los índices de los elementos inician en 0 y el último elemento está en la posición ``longitud_vector-1``
o ``número_filas/columnas-1``, similar a otros lenguajes de programación como C. 

Cuando se trata de acceder a elementos fuera del arreglo se genera el mensaje de error **IndexError**. 

Hay que tener en cuenta que los índices negativos se tratan como accesos desde el final del arreglo. Por ejemplo, acceder al elemento de la posición -1 es equivalente al acceso al último elemento, y -2 al penúltimo, etc.

Los valores de posición, fila o columna no necesariamente tienen que ser escalares, pueden ser vectores, de esta forma, Python devuelve un subvector o submatriz que contiene los elementos indicados. A continuación se ilustran algunos ejemplos.

In [25]:
v3 = np.array([2,-3,7,1,3,-2,5,8,6,4])
e1 = v3[7] 
print(e1)  #e1=8
e2 = v3[-1]
print(e2) #e2 = último elemento
v4 = v3[4:6]
print(v4)  #v4 = [v3[4],v3[5]] = [3,-2]
v5 = v3[[1,5,7]] #v5 = [v3[1],v3[5],v3[7]] = [-3, -2, 8]
print(v5)

8
4
[ 3 -2]
[-3 -2  8]


Se pueden alterar elementos individuales o un conjunto de elementos de una matriz o vector usando el mismo principio:
* ``vector[posiciones] = elementos``
* ``matriz[filas,columnas] = elementos``

En el siguiente ejemplo, los elementos de las posiciones 4, 6 y 8 son sustituidos por los números 0, 1 y 2:

In [26]:
v3 = np.array([2,-3,7,1,3,-2,5,8,6,4])
v3[[4,6,8]] = [0,1,2] 
print(v3)

[ 2 -3  7  1  0 -2  1  8  2  4]


de esta forma, esta línea de código es equivalente a las instrucciones:

In [27]:
v3[4] = 0
v3[6] = 1
v3[8] = 2

### A.4.1. Extraer submatrices

Se presenta a continuación otros ejemplos de acceso a elementos sobre una matriz. Siendo $A = \left[\begin{array}{ccc}
3 & 2 & 6\\
1 & 0 & 3\\
5 & 1 & 2
\end{array}\right]$
se tiene:

1. Para extraer el elemento $a_{32}$: 

In [28]:
A = np.array([[3,2,6], [1,0,3], [5,1,2]])
a32 = A[2,1]
print(a32)

1


2. Para extraer una submatriz de A (las dos filas inferiores):

In [29]:
A2 = A[1:3, 0:3]
print(A2)

[[1 0 3]
 [5 1 2]]


3. Para extraer un vector con todos los elementos de la columna 1 de la matriz A:

In [30]:
v6 = A[:,0]
print(v6)

[3 1 5]


4. Para extraer en el vector con los elementos de la fila 3 de la matriz A:

In [31]:
v7 = A[2,:]
print(v7)

[5 1 2]


En los dos ejemplos anteriores se usó la constante : para indicar que se deben devolver todas los elementos de la
columna o fila especificada.

### A.4.2. Extraer el tamaño de vectores y matrices

Finalmente, cuando se requiera medir la longitud de vectores y el tamaño de matrices se usan los operadores ``len`` y ``shape`` de la siguiente forma:

1. Para obtener el tamaño del vector v3

In [32]:
tam1 = len(v3)
print(tam1)

10


2. Para obtener el número de filas y columnas de una matriz:

In [33]:
tam2 = A2.shape
print(tam2)

(2, 3)


En este caso, en ``tam2`` se retorna una tupla con los valores [2,3], donde ``tam2[0]`` es el número de filas de la
matriz y ``tam2[1]`` el número de columnas

# A.5. Comparaciones

Python incluye la estructura condicional if..then..else, cuya sintaxis es la siguiente:

**Formato 1**:
```python
if condición:
    código sí se cumple la condición
```

**Formato 2**:
```python
if condición:
    código sí se cumple la condición
else:
    código sí no se cumple la condición
```

**Formato 3**:
```python
if condición1:
    código sí se cumple la condición1
elif condición2:
    código sí se cumple la condición2
else:
    código sí no se cumple la condición1 y la condición2
```

Las condiciones se deben escribir usando los siguientes operadores de comparación aplicados únicamente a escalares: == , != (diferente), < , >, <=, >=. 

Python es muy sensible a la sangría del código, es decir, todas las sentencias dentro de una condición deben estar alineadas a la misma sangría para representar que es un bloque de instrucciones.

In [ ]:
#Ejemplo:
if i == j:
    A[i,j] = 2
elif np.abs(i-j) != 1:
    A[i,j] = -1
else:
    A[i,j] = 0

# A.6. Ciclos y optimizaciones


Aunque Python contiene las estructuras de programación ``for`` y ``while``, debe evitarse su uso para la realización de cálculos simples tales como la evaluación de funciones que toman vectores como argumentos de entrada y sumatorias, las cuales se pueden hacer más rápido si se usan funciones especializadas de la biblioteca NumPy.

La sintaxis de estas estructuras es la siguiente:
```python
for x in vector:
    instrucciones
```
y 
```python
while condición_de_repetición:
    instrucciones
```

donde ``vector`` especifica los valores que tomará la variable x en cada iteración. 

En el siguiente ejemplo se muestra la **peor forma** de usar un ciclo ``for`` para crear un vector donde cada elemento es seno de un vector de ángulos:

In [35]:
x = np.zeros((20,1))
n=0
for teta in np.arange(0, 2*np.pi, np.pi/10):
    x[n] = np.sin(teta)
    n=n+1
print(x)

[[ 0.00000000e+00]
 [ 3.09016994e-01]
 [ 5.87785252e-01]
 [ 8.09016994e-01]
 [ 9.51056516e-01]
 [ 1.00000000e+00]
 [ 9.51056516e-01]
 [ 8.09016994e-01]
 [ 5.87785252e-01]
 [ 3.09016994e-01]
 [ 1.22464680e-16]
 [-3.09016994e-01]
 [-5.87785252e-01]
 [-8.09016994e-01]
 [-9.51056516e-01]
 [-1.00000000e+00]
 [-9.51056516e-01]
 [-8.09016994e-01]
 [-5.87785252e-01]
 [-3.09016994e-01]]


**OPTIMIZACIÓN**: El código anterior no es la forma más eficiente de evaluar la función. Este programa se puede escribir más simple y con una ejecución más rápida de la siguiente forma:

In [36]:
teta=np.arange(0, 2*np.pi, np.pi/10)
x = np.sin(teta)
print(x)

[ 0.00000000e+00  3.09016994e-01  5.87785252e-01  8.09016994e-01
  9.51056516e-01  1.00000000e+00  9.51056516e-01  8.09016994e-01
  5.87785252e-01  3.09016994e-01  1.22464680e-16 -3.09016994e-01
 -5.87785252e-01 -8.09016994e-01 -9.51056516e-01 -1.00000000e+00
 -9.51056516e-01 -8.09016994e-01 -5.87785252e-01 -3.09016994e-01]


Otro ejemplo de optimización es el cálculo de la sumatoria para evaluar la energía de una señal:

In [37]:
v3 = np.array([2,-3,7,1,3,-2,5,8,6,4])

#Forma ineficiente de cálculo de la energía
energia = 0 
for n in range(0,len(v3)):
    energia = energia+np.pow(v3[n],2)
print(energia)

#Forma eficiente de cálculo de la energía
energia = np.sum(np.pow(v3,2))
print(energia)

217
217


Tanto los ciclos ``for`` como el ``while`` se pueden interrumpir por medio de la instrucción ``break``. Ejemplo:

In [ ]:
i = 1
y = 0
while x[i] != 0:
    y = y+x[i]
    if y > 100:
        break
    i = i+1

# A.7. Funciones

Al igual que todos los lenguajes de programación, en Python es posible crear funciones, lo cual se realiza con el comando ``def``:

```python
def nombre_función ( parámetro1 , parámetro 2 , ... , parámetro n):
  código_función
  return resultado
```
donde resultado puede ser valor escalar, un vector o una tupla del tipo ``(retorno1,retorno2, ..., retorno-m)`` en caso de que la función retorne múltiples valores.

En el siguiente ejemplo se muestra como crear y usar una función para calcular la energía de una señal.

In [39]:
#Definición de la señal/vector
v3 = np.array([2,-3,7,1,3,-2,5,8,6,4])

#Definición de la función para el cálculo de la energía
def energia(x):
    return np.sum(np.pow(x,2))

#Llamado a la función
E = energia(v3)
print(E)

217


# A.8 Uso de cuadernos Python

En entornos como VSCode, Jupyter o GoogleColab se pueden crear cuadernos Python (archivos de extensión ``.ipynb``). Estos cuadernos, a diferencia con los archivo de código puro Python (extensión ``.py``), pueden incluir celdas de código y texto con formato, usando un lenguaje de descripción de marcas llamado Markdown.

Estas celdas se crean en su entorno de programación usando un comandos especiales de su entorno. Por ejemplo en VSCode, existe un botón llamado ``+Code`` y ``+Markdown`` para crear una u otra celda. Y las celdas se pueden intercambiar de funcionalidad si fueron creadas con el estilo incorrecto.

Las celdas de código se caracterizan porque incluyen un botón de Play ▷ que permite ejecutarlas. Las celdas de texto por su parte, pueden ser editadas dando doble clic sobre la celda. Una vez finalice la edición de una celda de texto, debe guardarla para que su contenido sea renderizado por la herramienta. Por ejemplo, en VSCode debe dar clic en el botón V.

En Markdown, existen diferentes comandos para darle estilo al documento como se verá en las siguientes secciones.

## A.8.1 Títulos

Para los títulos emplee:

```Markdown
# Título Nivel 1
## Título Nivel 2
### Título Nivel 3

```
Lo cual produce la salida:

# Título Nivel 1
## Título Nivel 2
### Título Nivel 3

## A.8.2. Estilo de la fuente

Puede cambiar la fuente a **Negrilla**, _Inclinada_ o **_Negrilla e inclinada_** con:

```Markdown
**Negrilla**
_Inclinada_
**_Negrilla e inclinada_** 
```

## A.8.3. Listas y viñetas

Para incluir listas numeradas escriba:

```Markdown
1. Primera lista. Esto es un párrafo de prueba.
2. Segunda lista. Esto es otro párrafo de prueba.
```

Lo cual produce:
1. Primera lista. Esto es un párrafo de prueba.
2. Segunda lista. Esto es otro párrafo de prueba.

Para incluir listas con viñetas basta con incluir el carácter ``*`` en la primera línea

```Markdown
* Texto de la viñeta 1
* Texto de la viñeta 2
```
Lo cual produce:
* Texto de la viñeta 1
* Texto de la viñeta 2

## A.8.4. Imágenes

Puede incluir imágenes usando la siguiente sintaxis:
```Markdown
![Sistema Básico de Procesamiento Digital de Señales](../img/SistemaDSP.png)
```
![Sistema Básico de Procesamiento Digital de Señales](../img/SistemaDSP.png)

## A.8.5. Tablas

Para las tablas use el siguiente formato

```Markdown
|Columna1|Columna2|Columna3|
|----|----|----|
|item-fila1|item2|item3|
|item-fila2|item4|item5|
```
y Markdown calcula los anchos de las columnas automáticamente:
|Columna1|Columna2|Columna3|
|----|----|----|
|item-fila1|item2|item3|
|item-fila2|item4|item5|

# A.8.6. Ecuaciones

Las ecuaciones se pueden incluir en línea con el texto encerrándolas entre el signo ``$`` y se centran y ubican en una única línea usando el doble ``$$``. Dentro de los signos de ``$`` se deben escribir las ecuaciones en formato LaTEX. El siguiente ejemplo muestra como crear un texto con ecuaciones:

```Markdown
En un párrafo se pueden incluir símbolos como $\pi$ que sirven para escribir ecuaciones en línea como el área de un círculo $A=\pi \times r^{2}$ o centradas como el volumen del cono $V_2$: $$V_2=\frac{1}{3} \pi r^2 h$$
```

Lo cual produce la salida:

En un párrafo se pueden incluir símbolos como $\pi$ que sirven para escribir ecuaciones en línea como el área de un círculo $A=\pi \times r^{2}$ o centradas como el volumen del cono $V_2$: $$V_2=\frac{1}{3} \pi r^2 h$$

Para más estilos de ecuaciones debe consultar una guía de LaTEX.